services:
  api:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
      target: dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "1323:1323"
    volumes:
      - ..:/app
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_PORT: ${DB_PORT:-5432}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    name: ${POSTGRES_VOLUME:-postgres_data_default}
